M2M3/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(("mild.urls", "mild"), namespace="mild")),
]

mild/urls.py
from django.contrib import admin
from django.urls import path
from mild.views import *
from . import views
urlpatterns = [
    path("", SignUp.as_view(), name="signup"),
    path("login/", Login.as_view(), name="login"),
    path("activate/<int:uid>", Activate.as_view(), name="activate"),
    path("dashboard/", Dashboard.as_view(), name="dashboard"),
    path("delete/<int:uid>", Delete.as_view(), name="delete"),
    path("edit/<int:uid>", Edit.as_view(), name="edit"),
    path("logout/",Logout.as_view(), name="logout"),
    path("forgot/",views.forgot, name="forgot"),
    path("forgoten/<int:uid>",Forgoten.as_view(), name="forgoten"),


]

mild/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin

class MyUserManagement(BaseUserManager):
	def create_user(self, email, password):
		email = self.normalize_email(email)
		user = self.model(email=email)
		user.set_password(password)
		user.save(using=self._db)
		return user
	def create_superuser(self, email, password):
		email = self.normalize_email(email)
		user = self.model(email=email)
		user.set_password(password)
		user.is_superuser = True
		user.is_active = True
		user.is_staff = True
		user.save(using=self._db)
		return user

class MyUser(AbstractBaseUser, PermissionsMixin):
	email = models.EmailField(unique= True, max_length=50)
	fname = models.CharField(max_length=20, blank=True ,null=True)

	lname = models.CharField(max_length=10, blank=True ,null=True)
	dob = models.CharField(blank=True ,null=True ,max_length=10)



	phone_number = models.CharField(blank=True, null=True, max_length=33)
	# confirmpassword = models.CharField(blank=True, null=True, max_length=33)
	is_active = models.BooleanField(default=False)
	is_staff = models.BooleanField(default=False)
	USERNAME_FIELD = 'email'
	objects = MyUserManagement()
	def __str__(self):
		return str(self.email)

mild/forms.py
from django import forms
from mild.models import *

class SignUpForm(forms.ModelForm):
    class Meta:
        model =MyUser
        fields = ("__all__")

class EditForm(forms.ModelForm):
    class Meta:
        model =MyUser
        fields = ("email","fname","phone_number","lname","dob")
class ForgotForm(forms.ModelForm):
    class Meta:
        model=MyUser
        fields= ('email',)

mild/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.views import View
from mild.forms import *
from M2M3.settings import *
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage

from django.template.loader import render_to_string


class SignUp(View):
  
    def get(self, request):
        return render(request,"home.html")

    def post(self, request):
        params = request.POST
        print(params)
        form =SignUpForm(params)
        if form.is_valid():
            user = form.save()
            print("user: ", user.id)
            current_site = get_current_site(request)
            mail_subject = 'Activate your account.'
            message = "http://"+str(current_site.domain) + \
                "/activate/"+str(user.id)
            print("message: ", message)
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[user.email]
            )
            email.send() 
            user.set_password(params["password"])
            user.save()
            return HttpResponse('Please confirm your email address to complete the registration')
        else:
            return render(request, 'home.html', {'message': "User not created."})


class Activate(View):
    def get(self, request, uid):
        try:
            user =MyUser.objects.get(id=uid)
        except(TypeError, ValueError, OverflowError,MyUser.DoesNotExist):
            user = None
        if user is not None and user.is_active == False:
            user.is_active = True
            user.is_staff = True
            user.save()
            return redirect("mild:login")
        else:
            return HttpResponse('Activation link is invalid!')


class Login(View):
    def get(self, request):
        return render(request, "login.html")

    def post(self, request):
        params = request.POST
        user = authenticate(email=params["email"], password=params["password"])
        if user is not None and user.is_active == True:
            login(request, user)
            return redirect("mild:dashboard")
        return render(request, "login.html", {"message": "user does not exists."})


class Dashboard(View):
    def get(self, request):
        if request.user.is_authenticated:
            users =MyUser.objects.all()
            return render(request, 'dashboard.html', {"users": users})
        else:
            return redirect("mild:login")

 
class Delete(View):
    def get(self, request, uid):
        user =MyUser.objects.filter(id=uid).delete()
        return redirect("mild:dashboard")


class Edit(View):
    def get(self, request, uid):
        instance =MyUser.objects.get(id=uid)
        print(instance)
        return render(request, "edit.html", {"instance": instance,"uid":uid})

    def post(self, request, uid):
        instance =MyUser.objects.get(id=uid)
        print("instance: ", instance)
        print("request.POST: ", request.POST)
        form =EditForm(request.POST, instance=instance)

        if form.is_valid():
            form.save()
            print("new data saved")
            return redirect("mild:dashboard")
        return redirect("mild:dashboard")


class Logout(View):
    def get(self, request):
        logout(request)
        return render(request, "login.html")

def forgot(request):
    para= request.POST
    print(para)
    form = ForgotForm(para) 
    if request.method=="POST":
        email = request.POST["email"]
        sumit=MyUser.objects.all()
        
        for i in sumit:
            if (email==i.email):
                abc = i.id
            
        print(abc)
        email=request.POST["email"]
        current_site= get_current_site(request)
        mail_subject='set your password'
        message = "http://"+str(current_site.domain) + "/forgoten/"+str(abc)
        print("message:", message)
        to_email =email
        email = EmailMessage(
                mail_subject, message, to=[email]
            )
        email.send()
        return HttpResponse('link has been sent to your mail to set password')
    else:
    
        return render(request,'forgot.html')


class Forgoten(View):
    def get(self, request, uid):
        try:
            user =MyUser.objects.get(id=uid)
        except(TypeError, ValueError, OverflowError,MyUser.DoesNotExist):
            user = None
        if user is not None and user.is_active ==True:
            instance= MyUser.objects.get(id=uid)
            
            return render (request,"password.html",{"instance":instance,"uid":uid})
        else:
            return HttpResponse("Activation link is invalid")



            
    def POST(self, request, uid):
        instance=MyUser.objects.get(id=uid)
        password=request.POST["password"]
        instance.set_password(password)
        instance.save()
        return redirect("mild:login")

       




       
   

templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'activate' uid=uid%}
{% endautoescape %}

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Dashboard</title>
</head>

<style>
  body {
    background-color:whitesmoke;
  }

  table,
  th,
  td {
    text-align: center;
    border: 1px solid blue;
    text-decoration: none;
  }
</style>

<body>

  <a href="{% url 'mild:logout' %}"><span style="background-color: blue; color:floralwhite;    padding: 15px;    float: right; ">Logout</span></a>
  <h4 style="font-weight: bolder; color:black;    font-size: 36px;">Records</h4>
  <div class="container">
    <div align="center"><span style="color:white;">{{message}}</span></div>
    <table style="width: 100%;">
     
      <tr>

        <th>ID</th>
        <th>EMAIL</th>
        <th>FIRST NAME</th>
        <th>Last NAME</th>
        <th>D.O.B</th>

  
        <th>MOBILE NO.</th>
        <th>EDIT</th>
        <th>DELETE</th>
      </tr>
      {% for i in users %}
      <tr>
        
        <td>{{i.id}}</td>
       
        <td>{{i.email}}</td>
        <td>{{i.fname}}</td>
        <td>{{i.lname}}</td>
        <td>{{i.dob}}</td>

        <td>{{i.phone_number}}</td>
        <td><a href="{% url 'mild:edit' i.id %}" style="color:white; background-color:blue;text-decoration: none;">EDIT</a></td>
        <td><a href="{% url 'mild:delete' i.id %}" style="color:white; background-color:RED;text-decoration: none;">DELETE</a></td>
      </tr>
      {% endfor %}

    </table>
  </div>
</body>

</html>

templates/edit.html
  <!DOCTYPE html>
  <html>
  <style>
  input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }
  
  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }
  
  input[type=submit]:hover {
    background-color: #45a049;
  }
  
  div {
    border-radius: 5px;
    background-color:pink;
    padding: 20px;
  }
  </style>
  <body>
    <h1>Edit Your Details</h1>
  
  
  <div>
      <div align="center">
      
      <span style="color: red;">{{message}}</span></div>
    <form action="{% url 'mild:edit' uid %}" method="POST">
        {% csrf_token %}
      <label for="fname">Email</label><br>
      <input type="Email" id="email" name="email" maxlength="50" placeholder="{{instance.email}}" value="{{instance.email}}"><br>
  
      <label for="lname">First Name</label><br>
      <input type="name" id="lname" name="fname"maxlength="30"  placeholder="{{instance.fname}}" value="{{instance.fname}}"><br>
      <label for="lname">Last Name</label><br>
      <input type="name" id="lname" name="lname"maxlength="30"  placeholder="{{instance.lname}}" value="{{instance.lname}}"><br>
      <label for="lname">D.O.B</label><br>
      <input type="date" id="lname" name="dob"maxlength="10"  placeholder="{{instance.dob}}" value="{{instance.dob}}"><br>

      <label for="lname">Number</label><br>
      <input type="number" id="lname" name="phone_number" maxlength="10" placeholder="{{instance.phone_number}}" value="{{instance.phone_number}}"><br>
      
      <button type="submit" >Submit</button>
    </form>
  </div>
  
  </body>
  </html>
  

templates/forgot.html
</html>
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->

<head>
  <meta charset="UTF-8" />
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
  <title>forgot password </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
  <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
  <meta name="author" content="Codrops" />
  <link rel="shortcut icon" href="{% static '../favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/animate-custom.css' %}" />
</head>

<body>
  <div class="container">
    <!-- Codrops top bar -->
    <!-- <div class="codrops-top">
      <a href="">
        <strong>&laquo; Previous Demo: </strong>Responsive Content Navigator
      </a>
      <span class="right">
        <a
          href="{% static 'http://tympanus.net/codrops/2012/03/27/login-and-registration-form-with-html5-and-css3/' %}">
          <strong>Back to the Codrops Article</strong>
        </a>
      </span>
      <div class="clr"></div>
    </div> -->
    <!--/ Codrops top bar -->
    <header>
      <h1>Reset Your password</h1>
      <nav class="codrops-demos">
        <!-- <span>Click <strong>"Join us"</strong> to see the form switch</span> -->
        <!-- <a href="">Demo 1</a>
        <a href="">Demo 2</a>
                <a href="">Demo 3</a> -->
      </nav>
    </header>
    <section>
      <div id="container_demo">
        <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>
        <div id="wrapper">
          <div id="forgot class="animate form">
            <!-- <span style="color: red;">{{message}}</span></div> -->
            <form action="{% url 'mild:forgot' %}"   method="POST">
              {% csrf_token %}
              <h1>Reset Your password</h1>

              <p>
                <label for="fname">Email</label>
                <input type="Email" id="fname" name="email"  placeholder="Your Email.." onkeypress="validateE()" req>
                <span id="e_mail_error"></span>
                
              </p>
             

        

              <p class=" login button">
                <input type="submit" value="Next"/>
            
              </p>
              <!-- <p class="forgot button">
                <input type="submit" value="Forgot " />
              </p> -->
              <p class="change_link">
                Not a member yet ?
                <a href="/" class="to_register">Join us</a>
              </p>
            </form>

          </div>



        </div>
      </div>
    </section>
  </div>
  <div>
    {% for message in messages %}
    <h3> {{message}} </h3>
    {% endfor %}
  </div>
  <script>
    function validateE(){
  var Email = document.getElementById("fname").value;
  var i, val, f_val, len = Email.length;
  var res, patt = /[¬`!"£$%^&*()-+={}:;'~#<,>/?|]/i;
  email_status = 0;
  f_val = Email[0];
  for(i=0;i<len;i++)
  {
    email_status = 0;
    res = Email[i].match(patt);
    val = f_val.charCodeAt(0);
    if(res!=null)
    {
      document.getElementById("e_mail_error").innerHTML = res+" not allowed";
      break;
    }
    else if(f_val>=0 && f_val<=9)
    {
      document.getElementById("e_mail_error").innerHTML = "Number not allowed at beginning";
      break;
    }
    else if(val>=32&&val<=47 || val>=58&&val<=64 || val>=91&&val<=96 || val>=123&&val<=126)
    {
      document.getElementById("e_mail_error").innerHTML = "Can't start with special chars.";
      break;
    }
    else if(Email.charAt(len-4)!='.' && Email.charAt(len-3)!='.')
    {
      document.getElementById("e_mail_error").innerHTML = "Invalid email!";
      break;
    }
    else {
      document.getElementById("e_mail_error").innerHTML = "";
      email_status = 1;
    }
  }
  // document.getElementById("e_mail_error").innerHTML = email_status;
}

  </script>
</body>

</html>

templates/home.html
</html>
{% load static %}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6 lt8"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7 lt8"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8 lt8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->

<head>
  <meta charset="UTF-8" />
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">  -->
  <title>Login and Registration Form with HTML5 and CSS3</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Login and Registration Form with HTML5 and CSS3" />
  <meta name="keywords" content="html5, css3, form, switch, animation, :target, pseudo-class" />
  <meta name="author" content="Codrops" />
  <link rel="shortcut icon" href="{% static '../favicon.ico' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/demo.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/animate-custom.css' %}" />
 
</head>

<body>
  <div class="container">
    <!-- Codrops top bar -->
    <!-- <div class="codrops-top">
      <a href="">
        <strong>&laquo; Previous Demo: </strong>Responsive Content Navigator
      </a>
      <span class="right">
        <a
          href="{% static 'http://tympanus.net/codrops/2012/03/27/login-and-registration-form-with-html5-and-css3/' %}">
          <strong>Back to the Codrops Article</strong>
        </a>
      </span>
      <div class="clr"></div>
    </div> -->
    <!--/ Codrops top bar -->
    <header>
      <h1>Registration Form</h1>
      <nav class="codrops-demos">
        <span>Click <strong>"Join us"</strong> to see the form switch</span>
        <a href="login">Demo 1</a>
        <a href="login">Demo 2</a>
        <!-- <a href="login">Demo 3</a> -->
      </nav>
    </header>
    <section>
      <div id="container_demo">
        <!-- hidden anchor to stop jump http://www.css3create.com/Astuce-Empecher-le-scroll-avec-l-utilisation-de-target#wrap4  -->
        <a class="hiddenanchor" id="toregister"></a>
        <a class="hiddenanchor" id="tologin"></a>
        <div id="wrapper">


          <div id="register" class="animate form">
            <span style="color: red;">{{message}}</span></div>
          <form action="{% url 'mild:signup' %}"   method="POST">
            {% csrf_token %}
            <!-- <p>
                {% for message in messages %}
                <h3> {{message}} </h3>
                {% endfor %}
              </p> -->
            <h1> Sign up </h1>
           
            <p>
              <label for="fname">Email</label>
              
              <input type="text" id="email" name="email" placeholder="Your Email.." onkeypress="ValidateEmail();" >

              <span id="e_mail_error"></span>

            </p>
            <p>
              <label for="lname"> First Name</label>
             
              <input type="text"  id="fname" name="fname" placeholder="Your First Name.." onkeypress="Validatefname();">
              <span id="fname_error"></span>
            </p>
            <p>
              <label for="lname">Last Name</label>
              <input type="text" id="lname" name="lname" placeholder="Last Name.." onkeypress="Validatelanme()">
              
              <span id="lname_error"></span>
            </p>
            <p>
              <label for="lname">D.O.B</label>
              <input type="date" id="dob" name="dob"  max="2020-07-15" placeholder="Date Of Birth" onclick="Validatebdy()" ondblclick="Validatebdy()">
              <span id="dob_error"></span>
            </p>
            
            <p>
              <label for="lname">Number</label>
              <input type="number" id="number" name="phone_number"  placeholder="Your Number.." onkeypress="Validateno()">
              <span id="phone_error"></span>
           

            </p>
            <label for="lname">Password</label>
            <input type="password" id="pass" name="password"  placeholder="Your password.." onkeypress="Validatepass()">
            <span id="pass_error"></span>
            <p>
              <label for="lname">Confirm Password</label>
              <input type="password" id="cpass" name="confirmpassword"  placeholder="confirmpassword" onkeypress="validateCpass()">
              <span id="cpass_error"></span>

            </p>
            <p>
    
              <p class="signin button">
                <input type="submit" value="Sign up" />
              </p>
              <p class="change_link">
                Already a member ?
                <a href="login" class="to_register"> Go and log in </a>
              </p>
          </form>

        </div>

      </div>
  </div>
  </section>
  </div>
  <div>
    {% for message in messages %}
    <h3> {{message}} </h3>
    {% endfor %}
  </div>
 <script>
  function ValidateEmail(){
  var Email = document.getElementById("email").value;
  var i, val, f_val, len = Email.length;
  var res, patt = /[¬`!"£$%^&*()-+={}:;'~#<,>/?|]/i;
  email_status = 0;
  f_val = Email[0];
  for(i=0;i<len;i++)
  {
    email_status = 0;
    res = Email[i].match(patt);
    val = f_val.charCodeAt(0);
    if(res!=null)
    {
      document.getElementById("e_mail_error").innerHTML = res+" not allowed";
      break;
    }
    else if(f_val>=0 && f_val<=9)
    {
      document.getElementById("e_mail_error").innerHTML = "Number not allowed at beginning";
      break;
    }
    else if(val>=32&&val<=47 || val>=58&&val<=64 || val>=91&&val<=96 || val>=123&&val<=126)
    {
      document.getElementById("e_mail_error").innerHTML = "Can't start with speical char.";
      break;
    }
    else if(Email.charAt(len-4)!='.' && Email.charAt(len-3)!='.')
    {
      document.getElementById("e_mail_error").innerHTML = "Invalid email";
      break;
    }
    else {
      document.getElementById("e_mail_error").innerHTML = "";
      email_status = 1;
    }
  }
  // document.getElementById("e_mail_error").innerHTML = email_status;
}

          
  function Validatefname(){
  var Firstname = document.getElementById("fname").value;
  var i, val, len = Firstname.length;
  fname_status = 0;
  for(i=0;i<len;i++)
  {
    fname_status = 0;
    val = Firstname.charCodeAt(i);
    if(!isNaN(Firstname[i]))
    {
      document.getElementById("fname_error").innerHTML = "Numbers not allowed ";
      break;
    }
    else if(val>=32&&val<=47 || val>=58&&val<=64 || val>=91&&val<=96 || val>=123&&val<=126)
    {
      document.getElementById("fname_error").innerHTML = "Special chars. not allowed";
      break;
    }
    else if((len<3)||(len>15))
    {
      document.getElementById("fname_error").innerHTML = "The length must be between 3 to 15";
      break;
    }
    else
    {
      document.getElementById("fname_error").innerHTML = "";
      fname_status = 1;
    }
  }
 
}

function Validatelanme(){
  var Lastname = document.getElementById("lname").value;
  var i, val, len = Lastname.length;
  lname_status = 0;
  for(i=0;i<len;i++)
  {
    lname_status = 0;
    val = Lastname.charCodeAt(i);
    if(!isNaN(Lastname[i]))
    {
      document.getElementById("lname_error").innerHTML = "Numbers not allowed ";
      break;
    }
    else if(val>=32&&val<=47 || val>=58&&val<=64 || val>=91&&val<=96 || val>=123&&val<=126)
    {
      document.getElementById("lname_error").innerHTML = "Special chars not allowed";
      break;
    }
    else if((len<3)||(len>15))
    {
      document.getElementById("lname_error").innerHTML = "The length must be between 3 to 15";
      break;
    }
    else
    {
      document.getElementById("lname_error").innerHTML = "";
      lname_status = 1;
    }
  }
  
}

function Validatebdy(){
  // var DOB = document.getElementById("dob").value;
  dob_status = 0;
  var n = new Date();
  var d = n.getDate();
  var m = n.getMonth();
  var y = n.getFullYear();
  m += 1;

  var dt = d/10;
  var mn = m/10;
  if(dt<1 && mn<1)
  {
    today_date = y+"-0"+m+"-0"+d;
  }
  else if(dt>=1 && mn<1)
  {
    today_date = y+"-0"+m+"-"+d;
  }
  else if(dt<1 && mn>=1)
  {
    today_date = y+"-"+m+"-0"+d;
  }
  else{
    today_date = y+"-"+m+"-"+d;
  }
  document.getElementById("dob").max = today_date;
  dob_status = 1;
  document.getElementById("dob_error").innerHTML = today_date;
}

function Validateno(){
  var Phone = document.getElementById("number").value;
  var i, len = Phone.length;
  phone_status = 0;
  for(i=0;i<len;i++)
  {
    phone_status = 0;
    if(len<11 || len>11)
    {
      document.getElementById("phone_error").innerHTML = "12 digit Number with country code required";
      break;
    }
    else
    {
      document.getElementById("phone_error").innerHTML = "";
      phone_status = 1;
    }
  }
  
}

function Validatepass(){
  var Password = document.getElementById("pass").value;
  var len = Password.length;
  pass_status = 0;
  document.getElementById("cpass").disabled = true;
  if(len<7)
  {
    document.getElementById("pass_error").innerHTML = "Minimun length is 8";
  }
  else if(len>11)
  {
    document.getElementById("pass_error").innerHTML = "Maximum limit is 12";
  }
  else
  {
    document.getElementById("pass_error").innerHTML = "";
    document.getElementById("cpass").disabled = false;
    document.getElementById("cpass").blur();
    pass_status = 1;
  }
 
}

function validateCpass(){
  var CPassword = document.getElementById("cpass").value;
  var Password = document.getElementById("pass").value;
  cpass_status = 0;
  if(Password == CPassword)
  {
    document.getElementById("cpass_error").innerHTML = "";
    cpass_status = 1;
  }
  else
  {
    document.getElementById("cpass_error").innerHTML = "Password doesnot match";
    cpass_status = 0;
  }
  // document.getElementById("cpass_error").innerHTML = cpass_status;
}


 </script>
</body>

</html>